"""
作者: BruceLee

文件职责: 汇总 BulletTrade 独立市场数据能力、路由、订阅、事件、Feed 与注册表合同。
主要输入: 调用方从本包导入的公开类型、工厂和错误类型。
主要输出: 稳定且不触发网络、SDK 加载或 backend 初始化的公共 Python API。
上游关系: 由 capability、models、feed 和 registry 模块提供具体实现。
下游关系: 供未来 LiveEngine、Huaxin integration、远程协议、策略和测试按需导入。
关键配置约定: 导入本包必须保持无副作用；本切片不注册任何厂商 backend。
"""

from .capability import (
    CapabilityDeclaration,
    CapabilityManifest,
    CapabilityReadiness,
    CapabilityRequest,
    CapabilitySupport,
    DataCapabilityError,
    DataCapabilityExecutionError,
    DataCapabilityNotReadyError,
    DataCapabilityRouteError,
    DataCapabilityUnavailableError,
    DataSourceRouter,
    ProviderLocation,
    RouteDecision,
    RouteRule,
    StrategyCapabilityPreflight,
    StrategyCapabilityProfile,
    StrategyCapabilityRequirements,
)
from .codec import (
    MarketEventCodecError,
    UnsupportedMarketEventSchemaError,
    dumps_market_event,
    loads_market_event,
    market_event_from_wire,
    market_event_to_wire,
)
from .feed import (
    FeedNotConnectedError,
    MarketDataFeedError,
    MarketEventCallback,
    MockRealtimeMarketDataFeed,
    RealtimeDataUnavailableError,
    RealtimeMarketDataFeed,
    SubscriptionConflictError,
    SubscriptionNotFoundError,
    TickCallback,
)
from .models import (
    CompatibilityTickEvent,
    ConnectionStateEvent,
    ConsolidatedTickEvent,
    DepthSnapshotEvent,
    FeedHealth,
    FieldProfile,
    IopvEvent,
    MarketDataLevel,
    MarketEvent,
    MarketEventRoute,
    MarketEventType,
    MarketStatusEvent,
    MarketSubscriptionReceipt,
    MarketSubscriptionSpec,
    OrderDetailEvent,
    QuoteSnapshotEvent,
    SecurityStatusEvent,
    SequenceGapEvent,
    SourceSequence,
    SubscriptionItemResult,
    SubscriptionItemState,
    SubscriptionSelector,
    SubscriptionState,
    TransactionEvent,
)
from .queue import (
    BoundedMarketEventQueue,
    MarketEventDrainBatch,
    MarketEventQueueMetrics,
    QueuePutOutcome,
    QueuePutResult,
)
from .registry import (
    FeedFactory,
    MarketDataFeedAlreadyRegisteredError,
    MarketDataFeedRegistration,
    MarketDataFeedRegistry,
    MarketDataFeedRegistryError,
    UnknownMarketDataFeedError,
    default_market_data_feed_registry,
)
from .subscriptions import (
    AdapterSubscriptionAction,
    AdapterSubscriptionFailure,
    AdapterSubscriptionOperation,
    AdapterSubscriptionScope,
    SessionSubscriptionLease,
    StaleSubscriptionActionError,
    SubscriptionLeaseConflictError,
    SubscriptionLeaseError,
    SubscriptionLeaseManager,
    SubscriptionLeaseNotFoundError,
    SubscriptionLeaseSnapshot,
    SubscriptionTransitionError,
)

__all__ = [
    "AdapterSubscriptionAction",
    "AdapterSubscriptionFailure",
    "AdapterSubscriptionOperation",
    "AdapterSubscriptionScope",
    "BoundedMarketEventQueue",
    "CapabilityDeclaration",
    "CapabilityManifest",
    "CapabilityReadiness",
    "CapabilityRequest",
    "CapabilitySupport",
    "CompatibilityTickEvent",
    "ConnectionStateEvent",
    "ConsolidatedTickEvent",
    "DataCapabilityError",
    "DataCapabilityExecutionError",
    "DataCapabilityNotReadyError",
    "DataCapabilityRouteError",
    "DataCapabilityUnavailableError",
    "DataSourceRouter",
    "DepthSnapshotEvent",
    "FeedFactory",
    "FeedHealth",
    "FeedNotConnectedError",
    "FieldProfile",
    "IopvEvent",
    "MarketDataFeedAlreadyRegisteredError",
    "MarketDataFeedError",
    "MarketDataFeedRegistration",
    "MarketDataFeedRegistry",
    "MarketDataFeedRegistryError",
    "MarketDataLevel",
    "MarketEvent",
    "MarketEventCallback",
    "MarketEventCodecError",
    "MarketEventRoute",
    "MarketEventType",
    "MarketEventDrainBatch",
    "MarketEventQueueMetrics",
    "MarketStatusEvent",
    "MarketSubscriptionReceipt",
    "MarketSubscriptionSpec",
    "MockRealtimeMarketDataFeed",
    "OrderDetailEvent",
    "ProviderLocation",
    "QueuePutOutcome",
    "QueuePutResult",
    "QuoteSnapshotEvent",
    "RealtimeDataUnavailableError",
    "RealtimeMarketDataFeed",
    "RouteDecision",
    "RouteRule",
    "SecurityStatusEvent",
    "SessionSubscriptionLease",
    "SequenceGapEvent",
    "SourceSequence",
    "StrategyCapabilityPreflight",
    "StrategyCapabilityProfile",
    "StrategyCapabilityRequirements",
    "StaleSubscriptionActionError",
    "SubscriptionConflictError",
    "SubscriptionItemResult",
    "SubscriptionItemState",
    "SubscriptionLeaseConflictError",
    "SubscriptionLeaseError",
    "SubscriptionLeaseManager",
    "SubscriptionLeaseNotFoundError",
    "SubscriptionLeaseSnapshot",
    "SubscriptionNotFoundError",
    "SubscriptionSelector",
    "SubscriptionState",
    "SubscriptionTransitionError",
    "TickCallback",
    "TransactionEvent",
    "UnknownMarketDataFeedError",
    "UnsupportedMarketEventSchemaError",
    "default_market_data_feed_registry",
    "dumps_market_event",
    "loads_market_event",
    "market_event_from_wire",
    "market_event_to_wire",
]
